---
apiVersion: v1
kind: Secret
metadata:
  name: rhteddyblr-wheres-teddy-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/WindTurbineInc/rhteddyblr-wheres-teddy-gitops
